=== RUN  TestCustomContextAfterFuncCancel
Exception: :context.withCancel is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfunccancel_testCustomContextAfterFuncCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15787:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestCustomContextAfterFuncCancel

=== RUN  TestCustomContextAfterFuncTimeout
Exception: :context.withTimeout is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfunctimeout_testCustomContextAfterFuncTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15874:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestCustomContextAfterFuncTimeout

=== RUN  TestCustomContextAfterFuncAfterFunc
Exception: :context.afterFunc is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfuncafterfunc_testCustomContextAfterFuncAfterFunc [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15700:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestCustomContextAfterFuncAfterFunc

=== RUN  TestCustomContextAfterFuncUnregisterCancel
Exception: :context.withCancel is not yet implemented
Called from .stdgo__$internal_context_Context_$withcancel_withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 17712 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfuncunregistercancel_testCustomContextAfterFuncUnregisterCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15922:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCustomContextAfterFuncUnregisterCancel

=== RUN  TestCustomContextAfterFuncUnregisterTimeout
Exception: :context.withTimeout is not yet implemented
Called from .stdgo__$internal_context_Context_$withtimeout_withTimeout (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 18010 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfuncunregistertimeout_testCustomContextAfterFuncUnregisterTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15964:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCustomContextAfterFuncUnregisterTimeout

=== RUN  TestCustomContextAfterFuncUnregisterAfterFunc
Exception: :context.afterFunc is not yet implemented
Called from .stdgo__$internal_context_Context_$afterfunc_afterFunc (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 18022 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfuncunregisterafterfunc_testCustomContextAfterFuncUnregisterAfterFunc [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15881:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCustomContextAfterFuncUnregisterAfterFunc

=== RUN  TestDeadlineExceededIsNetError
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48912 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48863 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:48401:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testdeadlineexceededisneterror_testDeadlineExceededIsNetError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16242:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)

-- FAIL: TestDeadlineExceededIsNetError

=== RUN  TestParentFinishesChild
Exception: :context.xTestParentFinishesChild is not yet implemented
Called from .stdgo__$internal_context_Context_$xtestparentfinisheschild_xTestParentFinishesChild (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20706 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testparentfinisheschild_testParentFinishesChild [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16485:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestParentFinishesChild

=== RUN  TestChildFinishesFirst
Exception: :context.xTestChildFinishesFirst is not yet implemented
Called from .stdgo__$internal_context_Context_$xtestchildfinishesfirst_xTestChildFinishesFirst (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20841 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testchildfinishesfirst_testChildFinishesFirst [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15604:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChildFinishesFirst

=== RUN  TestCancelRemoves
Exception: :context.xTestCancelRemoves is not yet implemented
Called from .stdgo__$internal_context_Context_$xtestcancelremoves_xTestCancelRemoves (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20844 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcancelremoves_testCancelRemoves [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15393:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCancelRemoves

=== RUN  TestCustomContextGoroutines
Exception: :context.xTestCustomContextGoroutines is not yet implemented
Called from .stdgo__$internal_context_Context_$xtestcustomcontextgoroutines_xTestCustomContextGoroutines (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20847 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextgoroutines_testCustomContextGoroutines [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16005:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCustomContextGoroutines

=== RUN  TestBackground
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testbackground_testBackground [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15325:11)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestBackground

=== RUN  TestTODO
Exception: :context.tODO is not yet implemented
Called from .stdgo__$internal_context_Context_$todo_tODO (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 36343 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testtodo_testTODO [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16758:11)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestTODO

=== RUN  TestWithCancel
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testwithcancel_testWithCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:17100:72)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestWithCancel

=== RUN  TestDeadline
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testdeadline_testDeadline [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16127:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestDeadline

=== RUN  TestTimeout
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testtimeout_testTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16724:74)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestTimeout

=== RUN  TestCanceledTimeout
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcanceledtimeout_testCanceledTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15357:74)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCanceledTimeout

=== RUN  TestValues
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testvalues_testValues [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16987:12)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestValues

=== RUN  TestAllocs
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testallocs_testAllocs [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15275:12)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestAllocs

=== RUN  TestSimultaneousCancels
Exception: :context.background is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testsimultaneouscancels_testSimultaneousCancels [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16717:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestSimultaneousCancels

=== RUN  TestInterlockedCancels
Exception: :context.background is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testinterlockedcancels_testInterlockedCancels [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16452:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestInterlockedCancels

=== RUN  TestLayersCancel
Exception: :context.background is not yet implemented
Called from ._$internal_context_$test_Context_$test_$_$testlayers__testLayers (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 12483 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testlayerscancel_testLayersCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16479:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLayersCancel

=== RUN  TestLayersTimeout
Exception: :context.background is not yet implemented
Called from ._$internal_context_$test_Context_$test_$_$testlayers__testLayers (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 12483 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testlayerstimeout_testLayersTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16482:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLayersTimeout

=== RUN  TestWithCancelCanceledParent
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testwithcancelcanceledparent_testWithCancelCanceledParent [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:17190:82)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestWithCancelCanceledParent

=== RUN  TestWithCancelSimultaneouslyCanceledParent
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testwithcancelsimultaneouslycanceledparent_testWithCancelSimultaneouslyCanceledParent [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:17233:83)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestWithCancelSimultaneouslyCanceledParent

=== RUN  TestWithValueChecksKey
panic = <invalid reflect.Value>; want %!q(MISSING)

-- FAIL: TestWithValueChecksKey

=== RUN  TestInvalidDerivedFail

-- PASS: TestInvalidDerivedFail

=== RUN  TestDeadlineExceededSupportsTimeout
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48912 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48863 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:48401:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testdeadlineexceededsupportstimeout_testDeadlineExceededSupportsTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16312:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)

-- FAIL: TestDeadlineExceededSupportsTimeout

=== RUN  TestCause
- SUBRUN  Background
Exception: :context.background is not yet implemented
Called from module at Object.stdgo__$internal_context_Context_$background_background [as _ctx] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:20850:23)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:15562:25
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 36939 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcause_testCause [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15559:51)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)

-- FAIL: TestCause

=== RUN  TestCauseRace
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcauserace_testCauseRace [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15583:82)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCauseRace

=== RUN  TestWithoutCancel
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testwithoutcancel_testWithoutCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:17269:67)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestWithoutCancel

=== RUN  TestCustomContextPropagation
Exception: :context.background is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextpropagation_testCustomContextPropagation [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:16120:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestCustomContextPropagation

=== RUN  TestAfterFuncCalledAfterCancel
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfunccalledaftercancel_testAfterFuncCalledAfterCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:14905:72)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestAfterFuncCalledAfterCancel

=== RUN  TestAfterFuncCalledAfterTimeout
Exception: :context.background is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfunccalledaftertimeout_testAfterFuncCalledAfterTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15076:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestAfterFuncCalledAfterTimeout

=== RUN  TestAfterFuncCalledImmediately
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfunccalledimmediately_testAfterFuncCalledImmediately [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15191:72)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestAfterFuncCalledImmediately

=== RUN  TestAfterFuncNotCalledAfterStop
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 20850 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfuncnotcalledafterstop_testAfterFuncNotCalledAfterStop [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15230:72)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestAfterFuncNotCalledAfterStop

=== RUN  TestAfterFuncCalledAsynchronously
Exception: :context.background is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfunccalledasynchronously_testAfterFuncCalledAsynchronously [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:15185:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 48178 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 42409 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:55163:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:55164:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestAfterFuncCalledAsynchronously

golibs/stdgo/_internal/testing/Testing_m_static_extension.hx:91: exitCode: 1 exitCodeReason: 
-- FAIL: TestAfterFuncCalledAsynchronously
