=== RUN  TestCustomContextAfterFuncCancel
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfunccancel_testCustomContextAfterFuncCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22658:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestCustomContextAfterFuncCancel

=== RUN  TestCustomContextAfterFuncTimeout
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfunctimeout_testCustomContextAfterFuncTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22745:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestCustomContextAfterFuncTimeout

=== RUN  TestCustomContextAfterFuncAfterFunc
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfuncafterfunc_testCustomContextAfterFuncAfterFunc [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22571:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestCustomContextAfterFuncAfterFunc

=== RUN  TestCustomContextAfterFuncUnregisterCancel
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$_$withcancel__withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24613 column 59)
Called from .stdgo__$internal_context_Context_$withcancel_withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24593 column 11)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfuncunregistercancel_testCustomContextAfterFuncUnregisterCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22793:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1

-- FAIL: TestCustomContextAfterFuncUnregisterCancel

=== RUN  TestCustomContextAfterFuncUnregisterTimeout
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from .stdgo__$internal_context_Context_$withdeadlinecause_withDeadlineCause (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 29385 column 25)
Called from .stdgo__$internal_context_Context_$withdeadline_withDeadline (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 29233 column 9)
Called from .stdgo__$internal_context_Context_$withtimeout_withTimeout (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 29230 column 9)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfuncunregistertimeout_testCustomContextAfterFuncUnregisterTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22835:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)

-- FAIL: TestCustomContextAfterFuncUnregisterTimeout

=== RUN  TestCustomContextAfterFuncUnregisterAfterFunc
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$afterfunc_afterFunc (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 32631 column 59)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextafterfuncunregisterafterfunc_testCustomContextAfterFuncUnregisterAfterFunc [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22752:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)

-- FAIL: TestCustomContextAfterFuncUnregisterAfterFunc

=== RUN  TestDeadlineExceededIsNetError

-- PASS: TestDeadlineExceededIsNetError

=== RUN  TestParentFinishesChild
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from .stdgo__$internal_context_Context_$xtestparentfinisheschild_xTestParentFinishesChild (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 33785 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testparentfinisheschild_testParentFinishesChild [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:23356:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestParentFinishesChild

=== RUN  TestChildFinishesFirst
Exception: Cannot read properties of undefined (reading '_common')
Called from .stdgo__$internal_context_Context_$xtestchildfinishesfirst_xTestChildFinishesFirst (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 35730 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testchildfinishesfirst_testChildFinishesFirst [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22475:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChildFinishesFirst

=== RUN  TestCancelRemoves
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$_$withcancel__withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24613 column 59)
Called from .stdgo__$internal_context_Context_$withcancel_withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24593 column 11)
Called from .stdgo__$internal_context_Context_$xtestcancelremoves_xTestCancelRemoves (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 36516 column 16)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcancelremoves_testCancelRemoves [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22120:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)

-- FAIL: TestCancelRemoves

=== RUN  TestCustomContextGoroutines
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from .stdgo__$internal_context_Context_$xtestcustomcontextgoroutines_xTestCustomContextGoroutines (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 36739 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextgoroutines_testCustomContextGoroutines [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22876:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCustomContextGoroutines

=== RUN  TestBackground

-- PASS: TestBackground

=== RUN  TestTODO

-- PASS: TestTODO

=== RUN  TestWithCancel
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$_$withcancel__withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24613 column 59)
Called from .stdgo__$internal_context_Context_$withcancel_withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24593 column 11)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testwithcancel_testWithCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:23987:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1

-- FAIL: TestWithCancel

=== RUN  TestDeadline
Exception: T_:testing.deadline is not yet implemented
Called from ._$internal_context_$test_Context_$test_$_$testdeadline__testDeadline (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 18814 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testdeadline_testDeadline [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:23011:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestDeadline

=== RUN  TestTimeout
Exception: T_:testing.deadline is not yet implemented
Called from ._$internal_context_$test_Context_$test_$_$testdeadline__testDeadline (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 18814 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testtimeout_testTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:23610:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestTimeout

=== RUN  TestCanceledTimeout
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from .stdgo__$internal_context_Context_$withdeadlinecause_withDeadlineCause (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 29385 column 25)
Called from .stdgo__$internal_context_Context_$withdeadline_withDeadline (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 29233 column 9)
Called from .stdgo__$internal_context_Context_$withtimeout_withTimeout (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 29230 column 9)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcanceledtimeout_testCanceledTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22088:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)

-- FAIL: TestCanceledTimeout

=== RUN  TestValues
<invalid reflect.Value>.Value(k2).(string) = %!q(MISSING), %!t(MISSING) want %!q(MISSING), %!t(MISSING)
c.String() = <invalid reflect.Value> want %!q(MISSING)
<invalid reflect.Value>.Value(k1).(string) = %!q(MISSING), %!t(MISSING) want %!q(MISSING), %!t(MISSING)
<invalid reflect.Value>.Value(k1).(string) = %!q(MISSING), %!t(MISSING) want %!q(MISSING), %!t(MISSING)
<invalid reflect.Value>.Value(k2).(string) = %!q(MISSING), %!t(MISSING) want %!q(MISSING), %!t(MISSING)
<invalid reflect.Value>.Value(k2).(string) = %!q(MISSING), %!t(MISSING) want %!q(MISSING), %!t(MISSING)
<invalid reflect.Value>.Value(k1).(string) = %!q(MISSING), %!t(MISSING) want %!q(MISSING), %!t(MISSING)
<invalid reflect.Value>.Value(k2).(string) = %!q(MISSING), %!t(MISSING) want %!q(MISSING), %!t(MISSING)
<invalid reflect.Value>.Value(k2).(string) = %!q(MISSING), %!t(MISSING) want %!q(MISSING), %!t(MISSING)

-- FAIL: TestValues

=== RUN  TestAllocs
golibs/stdgo/_internal/testing/Testing_allocsperrun.hx:3: allocsPerRun not implemented
golibs/stdgo/_internal/testing/Testing_allocsperrun.hx:3: allocsPerRun not implemented
golibs/stdgo/_internal/testing/Testing_allocsperrun.hx:3: allocsPerRun not implemented
golibs/stdgo/_internal/testing/Testing_allocsperrun.hx:3: allocsPerRun not implemented
golibs/stdgo/_internal/testing/Testing_allocsperrun.hx:3: allocsPerRun not implemented

-- PASS: TestAllocs

=== RUN  TestSimultaneousCancels
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testsimultaneouscancels_testSimultaneousCancels [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:23592:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestSimultaneousCancels

=== RUN  TestInterlockedCancels
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testinterlockedcancels_testInterlockedCancels [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:23323:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestInterlockedCancels

=== RUN  TestLayersCancel
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from ._$internal_context_$test_Context_$test_$_$testlayers__testLayers (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 19140 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testlayerscancel_testLayersCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:23350:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLayersCancel

=== RUN  TestLayersTimeout
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from ._$internal_context_$test_Context_$test_$_$testlayers__testLayers (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 19140 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testlayerstimeout_testLayersTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:23353:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLayersTimeout

=== RUN  TestWithCancelCanceledParent
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$_$withcancel__withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24613 column 59)
Called from .stdgo__$internal_context_Context_$withcancel_withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24593 column 11)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testwithcancelcanceledparent_testWithCancelCanceledParent [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:24074:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1

-- FAIL: TestWithCancelCanceledParent

=== RUN  TestWithCancelSimultaneouslyCanceledParent
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$_$withcancel__withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24613 column 59)
Called from .stdgo__$internal_context_Context_$withcancel_withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24593 column 11)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testwithcancelsimultaneouslycanceledparent_testWithCancelSimultaneouslyCanceledParent [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:24122:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1

-- FAIL: TestWithCancelSimultaneouslyCanceledParent

=== RUN  TestWithValueChecksKey

-- PASS: TestWithValueChecksKey

=== RUN  TestInvalidDerivedFail

-- PASS: TestInvalidDerivedFail

=== RUN  TestDeadlineExceededSupportsTimeout

-- PASS: TestDeadlineExceededSupportsTimeout

=== RUN  TestCause
- SUBRUN  Background
- SUBRUN  TODO
- SUBRUN  WithCancel
Cause(ctx) = <invalid reflect.Value> want %!v(MISSING)
- SUBRUN  WithCancelCause
Cause(ctx) = <invalid reflect.Value> want %!v(MISSING)
- SUBRUN  WithCancelCause nil
Cause(ctx) = <invalid reflect.Value> want %!v(MISSING)
- SUBRUN  WithCancelCause: parent cause before child
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$_$withcancel__withCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 24613 column 59)
Called from .stdgo__$internal_context_Context_$withcancelcause_withCancelCause (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 51912 column 11)
Called from Object._ctx (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 22300 column 18)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:22432:26
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 50287 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcause_testCause [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22429:52)

-- FAIL: TestCause

=== RUN  TestCauseRace
Exception: :runtime.gosched is not yet implemented
Called from .stdgo__$internal_runtime_Runtime_$gosched_gosched (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 52750 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcauserace_testCauseRace [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22471:3)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCauseRace

=== RUN  TestWithoutCancel

-- PASS: TestWithoutCancel

=== RUN  TestCustomContextPropagation
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testcustomcontextpropagation_testCustomContextPropagation [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:22991:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestCustomContextPropagation

=== RUN  TestAfterFuncCalledAfterCancel
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$afterfunc_afterFunc (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 32631 column 59)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfunccalledaftercancel_testAfterFuncCalledAfterCancel [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:21604:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)

-- FAIL: TestAfterFuncCalledAfterCancel

=== RUN  TestAfterFuncCalledAfterTimeout
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfunccalledaftertimeout_testAfterFuncCalledAfterTimeout [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:21769:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestAfterFuncCalledAfterTimeout

=== RUN  TestAfterFuncCalledImmediately
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$afterfunc_afterFunc (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 32631 column 59)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfunccalledimmediately_testAfterFuncCalledImmediately [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:21891:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)

-- FAIL: TestAfterFuncCalledImmediately

=== RUN  TestAfterFuncNotCalledAfterStop
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from stdgo__$internal_sync_atomic_$_Int32_$static_$extension.add (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 28971 column 23)
Called from stdgo__$internal_context_T_$cancelCtx_$static_$extension._propagateCancel (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 25145 column 58)
Called from .stdgo__$internal_context_Context_$afterfunc_afterFunc (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 32631 column 59)
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfuncnotcalledafterstop_testAfterFuncNotCalledAfterStop [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:21929:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)

-- FAIL: TestAfterFuncNotCalledAfterStop

=== RUN  TestAfterFuncCalledAsynchronously
golibs/stdgo/_internal/sync/atomic_/Atomic__int32_static_extension.hx:7: funclit
Exception: not implemented: add
Called from module at stdgo__$internal_testing_InternalTest._$internal_context_$test_Context_$test_$testafterfunccalledasynchronously_testAfterFuncCalledAsynchronously [as f] (/home/runner/work/go2hx/go2hx/golibs/std_context.js:21878:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 80998 column 9)
Called from ._$internal_contextdottest_Contextdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_context.js line 53820 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_context.js:88254:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_context.js:88255:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)

-- FAIL: TestAfterFuncCalledAsynchronously

golibs/stdgo/_internal/testing/Testing_m_static_extension.hx:91: exitCode: 1 exitCodeReason: 
-- FAIL: TestAfterFuncCalledAsynchronously
