=== RUN  TestFormatFileInfo

-- PASS: TestFormatFileInfo

=== RUN  TestFormatDirEntry

-- PASS: TestFormatDirEntry

=== RUN  TestValidPath

-- PASS: TestValidPath

=== RUN  TestGlob
Exception: ENOENT: no such file or directory, scandir ''
Called from .stdgo__$internal_io_fs_Fs_$readdir_readDir (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 24891 column 25)
Called from .stdgo__$internal_io_fs_Fs_$_$glob__glob (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 24631 column 16)
Called from .stdgo__$internal_io_fs_Fs_$_$globwithlimit__globWithLimit (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 21298 column 17)
Called from .stdgo__$internal_io_fs_Fs_$glob_glob (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 21187 column 16)
Called from module at stdgo__$internal_testing_InternalTest._$internal_io_fs_$test_Fs_$test_$testglob_testGlob [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:19517:17)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 48533 column 9)
Called from ._$internal_io_fsdottest_Fsdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 41807 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fs.js:55152:1

-- FAIL: TestGlob

=== RUN  TestGlobError

-- PASS: TestGlobError

=== RUN  TestCVE202230630
-- SKIP: testCVE202230630

-- PASS: TestCVE202230630

=== RUN  TestGlobMethod

-- PASS: TestGlobMethod

=== RUN  TestReadDir

-- PASS: TestReadDir

=== RUN  TestFileInfoToDirEntry
- SUBRUN  notadir.txt
- SUBRUN  adir

-- PASS: TestFileInfoToDirEntry

=== RUN  TestReadFile

-- PASS: TestReadFile

=== RUN  TestStat

-- PASS: TestStat

=== RUN  TestSub

-- PASS: TestSub

=== RUN  TestWalkDir

-- PASS: TestWalkDir

=== RUN  TestIssue51617
got directories <invalid reflect.Value>, want %!v(MISSING)
chmod: invalid mode: ‘448’
Try 'chmod --help' for more information.
node:fs:1581
  const result = binding.readdir(
                         ^

Error: EACCES: permission denied, scandir 'tmp_ldpiyh4q9h/a/bad'
    at Object.readdirSync (node:fs:1581:26)
    at deleteRecursively (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:46201:30)
    at deleteRecursively (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:46207:7)
    at deleteRecursively (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:46207:7)
    at stdgo__$internal_os_Os_$removeall_removeAll (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:46247:2)
    at /home/runner/work/go2hx/go2hx/golibs/std_fs.js:49151:4
    at stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:48544:4)
    at _$internal_io_fsdottest_Fsdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:41807:59)
    at /home/runner/work/go2hx/go2hx/golibs/std_fs.js:55152:1
    at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:55153:3) {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: 'tmp_ldpiyh4q9h/a/bad'
}

Node.js v23.11.1
